apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamus-example
  labels:
    app: kamus-example
spec:
  template:
    metadata:
      labels:
        app: kamus-example
    spec:
      serviceAccountName: kamus-example-sa
      automountServiceAccountToken: true
      containers:
        - name: app
          image: soluto/kamus-example-app
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: secret-volume
            mountPath: /secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: kamus-example-secret
